return {
  tilemap = {
    max_count = 16,
    max_tile_count = 2048,
  },
  engine = {
    max_time_step = 0.5,
    fixed_update_frequency = 60,
    run_while_iconified = 0,
  },
  project = {
    write_log = 0,
    title = "Look Don't Touch",
    title_as_file_name = "LookDontTouch",
    minimum_log_level = 1,
    developer = "unnamed",
    publisher = "unnamed",
    compress_archive = 1,
    version = 1,
  },
  ios = {
    launch_screen = "/builtins/manifests/ios/LaunchScreen.storyboardc",
    bundle_identifier = "example.unnamed",
    pre_renderered_icons = 0,
    bundle_name = "",
    default_language = "en",
    privacymanifest = "/builtins/manifests/ios/PrivacyInfo.xcprivacy",
    infoplist = "/builtins/manifests/ios/Info.plist",
    localizations = "en",
  },
  physics = {
    type = "2D",
    gravity_x = 0,
    gravity_z = 0,
    allow_dynamic_transforms = 1,
    ray_cast_limit_2d = 64,
    debug_scale = 30,
    ray_cast_limit_3d = 128,
    max_collisions = 64,
    max_contacts = 128,
    contact_impulse_limit = 0,
    max_collision_object_count = 128,
    use_fixed_timestep = 0,
    gravity_y = -10,
    max_fixed_timesteps = 2,
    debug_alpha = 0.9,
    velocity_threshold = 1,
    trigger_overlap_capacity = 16,
    world_count = 4,
    scale = 1,
    debug = 0,
  },
  label = {
    max_count = 64,
    subpixels = 1,
  },
  collection = {
    max_input_stack_entries = 16,
    max_instances = 1024,
  },
  script = {
    shared_state = 1,
  },
  gui = {
    max_animation_count = 1024,
    max_particle_count = 1024,
    max_count = 64,
    max_particlefx_count = 64,
  },
  mesh = {
    max_count = 128,
  },
  network = {
    ssl_certificates = "",
    http_thread_count = 4,
    http_timeout = 0,
    http_cache_enabled = 1,
  },
  library = {
    include_dirs = "",
  },
  particle_fx = {
    max_particle_count = 1024,
    max_count = 64,
    max_emitter_count = 64,
  },
  render = {
    clear_color_green = 0,
    clear_color_alpha = 1,
    clear_color_red = 0,
    clear_color_blue = 0,
  },
  input = {
    game_binding = "/input/game.input_bindingc",
    repeat_interval = 0.2,
    use_accelerometer = 1,
    gamepads = "/builtins/input/default.gamepadsc",
    repeat_delay = 0.5,
  },
  html5 = {
    archive_location_suffix = "",
    engine_arguments = "--verify-graphics-calls=false",
    custom_heap_size = 0,
    transparent_graphics_context = 0,
    wasm_streaming = 0,
    scale_mode = "downscale_fit",
    htmlfile = "/builtins/manifests/web/engine_template.html",
    show_fullscreen_button = 1,
    show_made_with_defold = 1,
    cssfile = "/builtins/manifests/web/light_theme.css",
    archive_location_prefix = "archive",
    show_console_banner = 1,
    heap_size = 256,
  },
  model = {
    max_count = 128,
    split_meshes = 0,
  },
  collection_proxy = {
    max_count = 8,
  },
  android = {
    target_sdk_version = 35,
    display_cutout = 1,
    debuggable = 0,
    gcm_sender_id = "",
    package = "com.example.todo",
    manifest = "/builtins/manifests/android/AndroidManifest.xml",
    extract_native_libs = 1,
    iap_provider = "GooglePlay",
    version_code = 1,
    input_method = "KeyEvent",
    proguard = "",
    minimum_sdk_version = 19,
    immersive_mode = 0,
  },
  osx = {
    bundle_version = 1,
    bundle_identifier = "example.unnamed",
    bundle_name = "",
    infoplist = "/builtins/manifests/osx/Info.plist",
    default_language = "en",
    privacymanifest = "/builtins/manifests/osx/PrivacyInfo.xcprivacy",
    app_icon = "",
    localizations = "en",
  },
  resource = {
    http_cache = 0,
    max_resources = 1024,
  },
  profiler = {
    sleep_between_server_updates = 0,
    track_cpu = 0,
    enabled = "true",
  },
  factory = {
    max_count = 128,
  },
  windows = {
    app_icon = "",
  },
  collectionfactory = {
    max_count = 128,
  },
  sprite = {
    max_count = 128,
    subpixels = 1,
  },
  sound = {
    max_sound_data = 128,
    max_sound_buffers = 32,
    max_sound_sources = 16,
    max_sound_instances = 256,
    max_component_count = 32,
    sample_frame_count = 0,
    use_thread = 1,
    stream_enabled = 0,
    stream_chunk_size = 16384,
    stream_preload_size = 16384,
    stream_cache_size = 2097152,
    gain = 1,
    use_linear_gain = 1,
  },
  shader = {
    output_spirv = 0,
  },
  liveupdate = {
    mount_on_start = 1,
    settings = "/liveupdate.settings",
    enabled = 1,
  },
  bootstrap = {
    render = "/builtins/render/default.renderc",
    main_collection = "/main/main.collectionc",
  },
  display = {
    display_device_info = 0,
    fullscreen = 0,
    high_dpi = 0,
    width = 960,
    height = 640,
    samples = 0,
    update_frequency = 0,
    swap_interval = 1,
    vsync = 1,
    dynamic_orientation = 0,
    display_profiles = "/builtins/render/default.display_profilesc",
  },
  graphics = {
    verify_graphics_calls = 1,
    max_draw_calls = 1024,
    max_characters = 8192,
    memory_size = 512,
    max_font_batches = 128,
    max_debug_vertices = 10000,
    opengl_core_profile_hint = 1,
    opengl_version_hint = 33,
    texture_profiles = "/builtins/graphics/default.texture_profiles",
    default_texture_mag_filter = "linear",
    default_texture_min_filter = "linear",
  },
}